# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2016-11-15 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='programms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coast', models.IntegerField()),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
